### ISSUE TITLE
Vorbereitung Praktikum

### ISSUE THREAD

**Issue by mschwrdtnr** [Donat24/BPA-factory-integration-and-simulation#6]
## Einfache Beschreibung
- Einführung Erläuterung der Architektur
- EC2 erstellen und vorbereiten
- Machine auf Basis eines Containers simulieren
- IoT Thing erstellen
- Alert Rule definieren
- Lambda Function zur Umwandlung des Payloads erstellen (vorgefertigte Funktion ergänzen)
- Datenobjekt in DynamoDB schreiben

![BPA_Praktikum](https://user-images.githubusercontent.com/39745446/119873608-0005b000-bf25-11eb-8cbb-44d6af24709e.png)

---

## Ausführlicherer Ablauf
- Einführung / Theoretischer Teil: Allgemein zu IoT und AWS
- Wir geben unserer Container vor, den Kommilitonen auf einem Server deployen sollen
- AWS IoT Thing erstellen
  - "Create Single..." (s-Nummer)
  - Create Certificates
  - Zertifikate herunterladen (CA, thing, private key)
  - Activate Certificate
  - Attach policy (von uns vorgegebene Policy)
- Server erstellen (Jeder sollte schon einen Server stehen haben)
  - Server vorbereiten (apt installs, scp certificate)
  - Container runterladen
  - Container starten
- Rule definieren, die Payload entgegen nimmt und Lambda triggert 
- Lambda Function erstellen
  - Erklärung zur Umwandlung Payload und warum wichtig
  - Umwandlung Payload in Message-Object: Vorgegebener Code, der vervollständigt werden muss
  - Nachricht in DynamoDB schreiben (Erklärung warum und was Alternative ist --> timeseries DB)

## Offene Fragen
- Wie lang soll Praktikum gehen?

**Comment by TamasJ** [comment]
Zu IoT Core einrichten ist das hier ja ziemlich straight forward: https://aws.amazon.com/premiumsupport/knowledge-center/iot-core-publish-mqtt-messages-python/ . Oder meine minimalistische deutsche Version, die da lautet:

Zunächst muss in AWS IoT Core unter Secure -> Policies eine Policy angelegt werden, welche im folgenden einem Thing hinzugefügt wird. Da das Hinzufügen (bei beschränkten Student-Rechten?) nur bei der Erstellung eines Things möglich ist, muss dies vor der Thing-Erstellung erfolgen. Hier können bereits Actions definiert und die vorgeschlagenen Resource IDs um selber festzulegende Topics und Client IDs erweitert werden.

Unter Manage -> Things kann ein Thing erstellt werden. Dabei können bereits die benötigten Zertifikate (für das Thing sowie AWS IoT root) und Schlüssel generiert, aktiviert und heruntergeladen werden. Im Anschluss daran kann die voher erstellte Policy zum Thing hinzugefügt werden und anschließend das Thing registriert werden.

Zur Verbindung mit AWS IoT Core nutzen wir mit Python den Mqtt-Client aus der Bibliothek AWSIoTPythonSDK (verfügbar über pip, from AWSIoTPythonSDK.MQTTLib import AWSIoTClient). Mit 'ASWIoTMQTTClient(clientId)' erstellen wir ein Client Objekt mit der in der Policy definierten Client ID. Der Host ist im Menü-Unterpunkt Interact als Rest API Entpoint aufzufinden, der Port ist standardmäßig 8883. Es bleiben noch die Pfadangaben für die Zertifikate und Private Key. 

myAWSIoTMQTTClient = AWSIoTMQTTClient(clientId)
myAWSIoTMQTTClient.configureEndpoint(host, port)
myAWSIoTMQTTClient.configureCredentials(rootCAPath, privateKeyPath, certificatePath)

Anschließend verbinden wir uns mit myAWSIoTMQTTClient.connect() (und abschließend analog disconnect).

Nachrichten können mit myAWSIoTMQTTClient.publish(topic, message, qos) veröffentlicht werden. Dabei ist die Topic jene in der Policy festgelegte, die Nachricht muss im Json-Format vorliegen, qos ist der gewünschte Quality-of-Service Level (zB 1 -> at least once).

https://aws.amazon.com/premiumsupport/knowledge-center/iot-core-publish-mqtt-messages-python/
